# Generated by Django 4.2.10 on 2024-08-20 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='balance_value',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
